### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by pollockm**
Changed "recieved" to "received"
...yes, this bothered me enough to make a pull request.

### CODE REVIEW

**Comment by JamesMc86** [comment]
haha thanks!

**Comment by pollockm** [comment]
np!  I'd also like a "prekill" option, to kill the selected LV process if it is already running.  Otherwise I sometimes get errors related to not getting the command line arguments.  My current workaround is to call a dummy vi with the --kill option before the real work.

**Comment by pollockm** [comment]
@JamesMc86  - I've also got a library of common CLI steps that I have up over here: https://github.com/LabVIEW-DCAF/buildsystem/tree/lv-cli/lv-steps

It's under Apache 2.0, so feel free to distribute as you see fit.

I'm planning on publishing those for NI Week, and including references to the CLI tool in my presentation.  You're attributed by name and I link back to this github page.  Do you mind if I use your logo on my slides when speaking about the tool?

**Comment by JamesMc86** [comment]
Of course feel free to mention the project and use any logo you need.

Those scripts look great - that is certainly the next step for me so I'll be looking to see what I can "borrow"

**Comment by pollockm** [comment]
Also, have you considered publishing the CLI on the tools network VIPM repo?  You could include the msi in the VIP file and have it install with the package.

I can toss in a pull request with that work if you like.

**Comment by JamesMc86** [comment]
@pollockm can you point me to your repo where you did this for putty?

**Comment by pollockm** [comment]
https://github.com/LabVIEW-DCAF/TagEditorCore/tree/master/source/Utilities/External%20tools

And in the tageditor core package, just called the post-install action.  No way around the windows user access control prompt, however.

**Pull request merged**
